project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "Driftless Spatial Planning Project, 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: evts.qmd
        text: Current Ecosystems
      - href: landforms.qmd
        text: Landforms
      - href: imi.qmd
        text: Moisture Index
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

